### ISSUE TITLE
User can summon a fox spirit animal 

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/ajax-project#1]
## 💰 Motivation
User wishes to generate an image with a fox 

## 📐 Plan
Create page with button to generate fox image 

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/11698908/127218095-3a351f77-7e87-4807-acab-f3ad6c84752a.png)
![image](https://user-images.githubusercontent.com/11698908/127206186-12698dd8-dc4e-45e4-ae70-20e6d67e9fc6.png)

## ✅ Task List
- [x] Create basic HTML 
- [x] Optimize for desktop
- [x] Optimize for mobile 
- [x] Event listener for button and its ilk
- [x] API call and parsing return data
- [x] Display image 
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
