### ISSUE TITLE
User can add fox spirit animal to collection or reject it

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/ajax-project#2]

**Comment by rskidmore1** [comment]
## 💰 Motivation
User has a choice in adding a fox to their collection
## 📐 Plan
Create functionality so a user can accepting the spirit animal will add it too the collection. Or reject it and  start over, letting the user summon a new spirit fox 

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/11698908/127255226-a30f55bc-cc48-4031-8195-4921934b20c7.png)
![image](https://user-images.githubusercontent.com/11698908/127255306-9b5e8585-6d80-494a-b378-245476fa508c.png)



## ✅ Task List
- [x] Show Accept and Reject Buttons after fox is "summoned"
- [x] Create data model to store in local storage
- [x] Create code for entering local storage and retrieving it
- [x] Create code to go back to the "summon" button screen 
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
