### ISSUE TITLE
User can view a collection of fox spirit animals 

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/ajax-project#3]

**Comment by rskidmore1** [comment]
## 💰 Motivation
User can view their collection of foxes 
## 📐 Plan
Create layout of foxes based in foxes stores in data model

## Notes
The quotes portion in wireframes is being built out in a future feature in conjunction with other functionality. 
## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/11698908/127388975-18ebe0e1-77ac-4679-8265-fd0a7100805e.png)
![image](https://user-images.githubusercontent.com/11698908/127389040-6b6eaf2c-a595-4e44-bca5-8bb6aa657c35.png)





## ✅ Task List
- [x] HTML: Create desktop layout
  - [x] Create boxes for each fox 
  - [x] Make clickable 
  - [x] Hover makes the gray darker
  - [x] change cursor
  - [x] Pull data from data model
- [x] HTML:Ensure adapted for mobile
  - [x] Fox squares stack when view port shrinks
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
