### ISSUE TITLE
User can release a fox spirit animal from collection

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/ajax-project#4]

**Comment by rskidmore1** [comment]
## 💰 Motivation
User can remove fox from collection to make room for a new one. The cap is 7 foxes in the collection
## 📐 Plan
Create profile. Create modal. Create buttons. Make the show the modal and remove current fox from local storage and DOM

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/11698908/127689367-4616b747-c0a2-4123-bfaa-dfaca0b0de3d.png)
![image](https://user-images.githubusercontent.com/11698908/127689467-673e86cd-58f3-45d1-a732-940af71276a4.png)
![image](https://user-images.githubusercontent.com/11698908/127689426-80c3db15-defb-4e5a-8634-e9ec42178e01.png)
![image](https://user-images.githubusercontent.com/11698908/127689521-826bb6d2-e813-41d6-8064-5320ae5fd832.png)


## ✅ Task List
- [x] HTML
  - [x] Make fox profile based on summon profile
  - [x] Change buttons
  - [x] Create modal
  - [x] Make them show a modal
  - [x] Create buttons for modal
- [x] Make modal 'Be Released' button remove the fox from local storage
- [x] Make modal button remove fox from DOM
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
