### ISSUE TITLE
User can request an anime quote from spirit animals 

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/ajax-project#5]

**Comment by rskidmore1** [comment]
## 💰 Motivation
User can get advice and more personality from the fox via a quote
## 📐 Plan
Pull from quote API via the quote button. Insert quote to local storage. Insert it into the collection beneith it fox

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/11698908/127582491-1d6ed8ee-1e73-4962-8bff-8ab33315d0e2.png)
![image](https://user-images.githubusercontent.com/11698908/127582524-5a566ef6-cf8c-424f-8503-3db504617908.png)
![image](https://user-images.githubusercontent.com/11698908/127582565-13c33028-ed37-43c6-8af4-2217651b09c1.png)
![image](https://user-images.githubusercontent.com/11698908/127582587-ae26a393-782d-4dee-9a04-dec2dd3855d7.png)

## ✅ Task List
- [x] Pull from quotes api when quote button pushed
- [x] Insert to data model
- [x] Insert into profile view 
- [x] Insert into collection view 
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
