### ISSUE TITLE
User can request a new quote from spirit animal to replace the animal’s last quote

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/ajax-project#6]

**Comment by rskidmore1** [comment]
## 💰 Motivation
User can replace their existing quote with a safe guard 
## 📐 Plan
Create modal asking if they want to replace or keep the current quote, Create JS to replace it or return to fox profile. 

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/11698908/127716197-aa980df3-57d8-4a29-9103-47fefc78a084.png)
![image](https://user-images.githubusercontent.com/11698908/127716231-8f95c2af-6758-48b7-a808-9420813f4a70.png)


## ✅ Task List
- [x] Create modal
- [x] Create buttons
- [x] Ensure it looks good on mobile 
- [x] Make "keep my quote" button do just that
- [x] Make "New quote" button do just that
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
